python -m scripts.base_train \
                            --pretrained-model-path ./Qwen3.5-0.8B \
                            --dataset-path /path/to/dataset \
                            --max-seq-len 4096 \
                            --num-iterations 1000000 \
                            --device-batch-size 16 \
                            --total-batch-size 131072 \
                            --embedding-lr 1e-5 \
                            --unembedding-lr 1e-5 \
                            --matrix-lr 1e-5 \
                            --scalar-lr 1e-5 \
                            --warmdown-ratio 0.1 \
                            --optimizer muon \
                            --weight-decay 0.1 \
                            --final-lr-frac 0.1 \
                            --eval-every 1000 \
                            --eval-tokens 6553600 \
                            --core-metric-every 1000 \
                            --core-metric-max-per-task 500 \
                            --sample-every 1000 \
                            --save-every 1000
